[package]
name = "rsdf_core"
version = "0.0.0"
edition = "2021"

[dependencies]
png = "0.17"
itertools = "0.10"
aberth = "0.0.3"
arrayvec = "0.7"
num-derive = "0.3"
num-traits = "0.2"
float-cmp = "0.9"
